# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sphinx application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_ACTOR: snehasish Das
  GITHUB_REPOSITORY: sndas1903/sphinx
  GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          cd sphinx
          chmod +x build.sh
          ls -lrt
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
        run: "sphinx/build.sh"
        shell: bash
